[bell]
animation = "EaseOutExpo"
command = "None"
duration = 0

# helmholtz color scheme from mintty:
# https://gist.github.com/przemoc/1d8e27c08b9e9fefda7d14baca36ef01
[colors.bright]
black = "#606060"
blue = "#7D97FF"
cyan = "#00F0F0"
green = "#00F200"
magenta = "#FF70FF"
red = "#FF7676"
white = "#FFFFFF"
yellow = "#F2F200"

[colors.normal]
black = "#000000"
blue = "#005DFF"
cyan = "#00A89A"
green = "#1CA800"
magenta = "#B148C6"
red = "#D42C3A"
white = "#BFBFBF"
yellow = "#C0A000"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[cursor]
style.blinking = "Off"
style.shape = "Block"

[font]
size = 11.0

[font.normal]
family = "Cascadia Mono"
style = "Medium"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[window]
opacity = 0.88
