[bell]
animation = "EaseOutExpo"
command = "None"
duration = 0

[colors.bright]
black = "#7f7f7f"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000ee"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
blinking = "Off"
shape = "Block"

[font]
size = 15.0

[font.normal]
family = "Terminus"
style = "Medium"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[window]
opacity = 0.88
