#!/bin/awk -f

# pre commit git to avoid committing TODO, FIXME, DEBUG, ... stuff by mistake
# copy/paste/rename in .git/hooks/pre-commit
# Requires awk (any: gawk, nawk, mawk, ...)
# See also githooks (5)

BEGIN {
    forbidden_regex = "TODO|FIXME|DEBUG"

    SEARCHING_FNAME = 0
    SEARCHING_MATCH = 1

    if (ENVIRON["COLUMNS"]) {
        MAX_GREP_COLUMNS = 3 * ENVIRON["COLUMNS"]
        if (MAX_GREP_COLUMNS < 20) {
            MAX_GREP_COLUMNS = 20
        }
    } else {
        MAX_GREP_COLUMNS = 300
    }

    state = SEARCHING_FNAME
    cmd = "git diff --staged -p -U0"
    forbidden_found = 0 # to print header only once & set exit status
    while ((cmd | getline) > 0) {
        if ($1 == "diff") {
            state = SEARCHING_FNAME
            fname_printed = 0
        } else if (state == SEARCHING_FNAME) {
            if ($1 == "+++") {
                fname = substr($0, 7) # remove "+++ b/" prefix
                state = SEARCHING_MATCH
            }
        } else if (state == SEARCHING_MATCH) {
            if ($0 ~ /^\+/ && toupper($0) ~ forbidden_regex) {
                if (!forbidden_found) {
                    print (forbidden_regex " forbbiden marks found:")
                    forbidden_found = 1
                }
                if (!fname_printed) {
                    printf("\n* %s:\n", fname)
                    fname_printed = 1
                }

                print_match($0)
            }
        }
    }
    close(cmd)

    if (forbidden_found) {
        printf("\nTo commit anyway, use the -n/--no-verify flag\n")
    }

    exit(forbidden_found)
}

function print_match(str) {
    # if the line is short we can just print all of it
    if (length(str) <= MAX_GREP_COLUMNS) {
        print(str)
        return
    }

    # handle long lines
    # NOTE: only printing 1st match to keep the algorithm somewhat simple

    match(str, forbidden_regex)
    if (RSTART + RLENGTH <= MAX_GREP_COLUMNS) {
        # match is near the line start: truncate the end
        print(substr(str, 1, MAX_GREP_COLUMNS) "... (truncated)")
    } else if (RSTART + RLENGTH > length(str) - (MAX_GREP_COLUMNS / 2)){
        # match is near the line end: truncate the start
        print(substr(str, 1, 1) "... (truncated) ..." \
              substr(str, length(str) - MAX_GREP_COLUMNS))
    } else {
        # match is in between the line: truncate both start & end
        print(substr(str, 1, 1) "... (truncated) ..." \
              substr(str, RSTART - (MAX_GREP_COLUMNS / 2), MAX_GREP_COLUMNS) \
              "... (truncated)")
    }
}
