#!/bin/awk -f

# pre commit git to avoid committing TODO, FIXME, DEBUG, ... stuff by mistake
# copy/paste/rename in .git/hooks/pre-commit
# Requires awk (any: gawk, nawk, mawk, ...)
# See also githooks (5)

BEGIN {
    forbidden_regex = "TODO|FIXME|DEBUG"

    SEARCHING_FNAME = 0
    SEARCHING_MATCH = 1

    state = SEARCHING_FNAME
    cmd = "git diff --staged -p -U0"
    forbidden_found = 0 # to print header only once & set exit status
    while ((cmd | getline) > 0) {
        if ($1 == "diff") {
            state = SEARCHING_FNAME
            fname_printed = 0
        } else if (state == SEARCHING_FNAME) {
            if ($1 == "+++") {
                fname = substr($0, 7) # remove "+++ b/" prefix
                state = SEARCHING_MATCH
            }
        } else if (state == SEARCHING_MATCH) {
            if ($0 ~ /^\+/ && toupper($0) ~ forbidden_regex) {
                if (!forbidden_found) {
                    print (forbidden_regex " forbbiden marks found:")
                    forbidden_found = 1
                }
                if (!fname_printed) {
                    printf("\n* %s:\n", fname)
                    fname_printed = 1
                }
                print($0)
            }
        }
    }
    close(cmd)

    if (forbidden_found) {
        printf("\nTo commit anyway, use the -n/--no-verify flag\n")
    }

    exit(forbidden_found)
}
