#
# /etc/wsl.conf: distro-wide WSL config
#
# see https://learn.microsoft.com/en-us/windows/wsl/wsl-config

[automount]
# do not mark every windows file as executable.
# (directories need to be executable to interact with them)
options = "umask=022,fmask=111"
